//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public int ID { get; set; }
        public string TEXT { get; set; }
        public int SESSION_ID { get; set; }
        public int QUESTION_ID { get; set; }
        public Nullable<int> QUESTION_OPTION_ID { get; set; }
    
        public virtual QUESTIONS_OPTIONS QUESTIONS_OPTIONS { get; set; }
        public virtual QUESTION QUESTION { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
