//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbStructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9AB8B7_D18DDA6043Entities : DbContext
    {
        public DB_9AB8B7_D18DDA6043Entities()
            : base("name=DB_9AB8B7_D18DDA6043Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANSWER> ANSWERS { get; set; }
        public virtual DbSet<QUESTION> QUESTIONS { get; set; }
        public virtual DbSet<QUESTIONS_OPTIONS> QUESTIONS_OPTIONS { get; set; }
        public virtual DbSet<SESSION> SESSIONS { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
    }
}
