//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUESTION()
        {
            this.ANSWERS = new HashSet<ANSWER>();
            this.QUESTIONS1 = new HashSet<QUESTION>();
            this.QUESTIONS_OPTIONS = new HashSet<QUESTIONS_OPTIONS>();
            this.QUESTIONS_OPTIONS1 = new HashSet<QUESTIONS_OPTIONS>();
        }
    
        public int ID { get; set; }
        public string TEXT { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> NEXT_QUESTION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWER> ANSWERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTION> QUESTIONS1 { get; set; }
        public virtual QUESTION QUESTION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTIONS_OPTIONS> QUESTIONS_OPTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUESTIONS_OPTIONS> QUESTIONS_OPTIONS1 { get; set; }
    }
}
