//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbStructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SESSION()
        {
            this.ANSWERS = new HashSet<ANSWER>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string GIVEN_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public string PHONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANSWER> ANSWERS { get; set; }
    }
}
